### ISSUE TITLE
Getting an error in build time: "Can't resolve"

### ISSUE THREAD

**Issue by moshfeu** [kingjan1999/platform-folders#9]
> ERROR in ./node_modules/platform-folders/dist/index.js
Module not found: Error: Can't resolve '../build/Release/platform-folders'

Node version: `v8.11.3`
Npm version: `6.4.1`.

Thanks!

**Comment by kingjan1999** [comment]
Hi,

sorry for the late response:
Thank you for your interest in my project. Unfortunately I don't have much time to spend on this right now, but I will look as this as soon as I've got more time to spare.

Sorry!

**Comment by moshfeu** [comment]
Thanks!

**Comment by LizAinslie** [comment]
i guess i'll use a different module... i need this for my electron/react app

**Comment by LizAinslie** [comment]
it would be great if this could be fixed soon. i can understand business, so i'll wait :)

**Comment by moshfeu** [comment]
@RailRunner166  which folder are youcusing in your project?

**Comment by LizAinslie** [comment]
documents, i made my own module to do it for me instead tho (more like cloned and heavily modified, but you know)

**Comment by moshfeu** [comment]
Interesting. Are implementing it with c++ and use module to only wrap it or are you doing it with pure node?

**Comment by LizAinslie** [comment]
pure node :3

**Comment by LizAinslie** [comment]
if you wanna check out my implementation, it's at https://github.com/MyRPC/documents-folder

**Comment by moshfeu** [comment]
Nice!

It's a little bit strange to be fork. Isn't better to clone?

**Comment by LizAinslie** [comment]
i forked one that was called `downloads-folder`

**Comment by moshfeu** [comment]
Yah, I saw is. I just wonder if isn't will be better to clone it. Because fork is meant to do pull requests or custom / extends the product for your needs. Not for a different product. That's what I know about how forks are working :)

**Comment by LizAinslie** [comment]
i extended it for my needs, but for future reference, how do i clone it (not to my computer, but to another repo)?

**Comment by moshfeu** [comment]
You can download the zip, extract it and [setup git on this repo](https://help.github.com/articles/adding-an-existing-project-to-github-using-the-command-line/)

**Comment by LizAinslie** [comment]
ah yes, that... i find forking to be simpler, and more straightforward, but thank you for the refresher.

**Comment by kingjan1999** [comment]
I've just published 0.3.2 which used n-api instead of node.h.
Hopefully this fixes some of the build related error (my tests on windows / ubuntu and the ci builds look very promising).

Would you mind giving it a second try (make sure to have node > 8)?

**Comment by moshfeu** [comment]
@kingjan1999, Thanks!

Just tried and I'm getting this error (in run time):

> Uncaught Error: Could not locate the bindings file. Tried:
 → ...path/build/platformFolders.node
 → ...path/build/Debug/platformFolders.node
 → ...path/build/Release/platformFolders.node
 → ...path/out/Debug/platformFolders.node
 → ...path/Debug/platformFolders.node
 → ...path/out/Release/platformFolders.node
 → ...path/Release/platformFolders.node
 → ...path/build/default/platformFolders.node
 → ...path/compiled/10.2.0/darwin/x64/platformFolders.node
 → ...path/addon-build/release/install-root/platformFolders.node
 → ...path/addon-build/debug/install-root/platformFolders.node
 → ...path/addon-build/default/install-root/platformFolders.node
 → ...path/lib/binding/node-v64-darwin-x64/platformFolders.node
    at bindings (bindings.js:124)
    at Object../node_modules/platform-folders/src/index.js (index.js:3)

Tried to remove `node_modules` and `install` again, same results.

**Node: v8.11.3**
**Npm: 6.5.0**
**OS: Mac 10.14.2**

**Comment by LizAinslie** [comment]
@kingjan1999 did the windows/ubuntu work? i would at least like to compile for those (which i have since i changed to my own package, but am having other issues still, so i'd like to use this).

**Comment by kingjan1999** [comment]
@moshfeu Thanks for you quick help!
As this is a run time error, I guess `npm install` (including the `node-gyp rebuild` step`) works fine?
I tried reproducing this on Travis CI (which can use mac os x) using similar specs (OS X 10.13, Node 8.15) and [it worked perfectly. ](https://travis-ci.org/kingjan1999/platform-folders-test/jobs/488094868)

Can you try cloning my minimal example: [kingjan1999/platform-folders-test](https://github.com/kingjan1999/platform-folders-test), running `npm install` and then `node index.js`? Does that result in the same error?

@RailRunner166 Yes, it worked for me (using the minimal example linked above)

**Comment by moshfeu** [comment]
Yes, this `npm install` is worked fine.
Also, your test project is working fine except for a warning:

> (node:18693) Warning: N-API is an experimental feature and could change at any time.

I'm not sure, maybe there is a problem with a combination with electron (or with my environment)

**Comment by kingjan1999** [comment]
I've just tried this in combination with electron (see electron branch on mentioned project) and it works fine out of the box (even though problems when combining [node native addons with electrons are quite plausible](https://electronjs.org/docs/tutorial/using-native-node-modules)) on both Ubuntu 18.04 (Electron 4.04, Node 11.4.0 and Node 8.15.0) and Mac OS X 10.14.3 (Electron 4.04, Node 10.14.2).

It really seems like a problem with your environment.

**Comment by LizAinslie** [comment]
@moshfeu i get the same error with electron, so i think its an electron thing

**Comment by LizAinslie** [comment]
liuckily i think we can safely close this now

**Comment by LizAinslie** [comment]
*luckily

**Comment by moshfeu** [comment]
@RailRunner166  I think you're right.
Thanks @kingjan1999
